[package]
edition = "2024"
name = "ili9488-stm32-rs"
version = "0.1.0"
authors = ["TESSON-MAKER <paul.tesson.officiel@gmail.com>"]
resolver = "2"

[[bin]]
name = "ili9488-stm32-rs"
test = false
bench = false

[dependencies]
defmt-rtt = "1.2"
panic-probe = { version = "1.0", features = ["print-defmt"] }

embassy-executor = { version = "0.10", features = ["platform-cortex-m", "executor-thread", "defmt", "executor-interrupt"] }
embassy-time = { version = "0.5", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-stm32 = { version = "0.6", features = ["defmt", "stm32f767zi", "unstable-pac", "memory-x", "time-driver-any", "single-bank" ] }

mipidsi = "0.10.0"
embedded-graphics = "0.8.2"
embedded-graphics-framebuf = "0.5.0"

embedded-graphics-profont = "0.4.0"
embedded-hal-bus = { version = "0.2.0" }
heapless = "0.9.3"
static_cell = "2.1"
ds323x = "0.7"
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }

[profile.release]
debug = 2
lto = true
opt-level = 'z'

[profile.dev]
debug = 2
lto = true
opt-level = "z"
